name: translator_automation
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  excel: ^4.0.6
  googleapis_auth: ^1.4.0
  googleapis: ^13.1.0
  http: ^0.13.6
  #connectivity_plus: ^6.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
